In [1]:
from cpg_fsm import *
from scipy.optimize import minimize
from scipy.optimize import differential_evolution

In [2]:
loop_freq = 100  # Hz
FSM = FiniteStateMachine(loop_freq)
t = time.time()
iter = 0

In [3]:
def getTrajectoryCost(bezier_profiles):
    global iter
    global t
    print("t", time.time()-t)
    t = time.time()
    bp = bezier_profiles.reshape(4, -1)
    print(bp[3])
    CORGI = Corgi(loop_freq, FSM)
    CORGI.standUp(0.8)
    CORGI.move(swing_profile=bp)
    print("iter", iter,"cost",CORGI.cost)
    iter += 1
    return CORGI.cost
    

In [4]:
bez_prof_init = np.array([[0.07, 0.01, 0.15, 0.05, 0.08, 0.06],
                          [0.07, 0.01, 0.15, 0.05, 0.08, 0.06],
                          [0.07, 0.01, 0.08, 0.05, 0.02, 0.1],
                          [0.07, 0.01, 0.08, 0.05, 0.02, 0.1]])
bez_prof_init = bez_prof_init.reshape(1, -1)[0]

step_height = 0.05
bnd_H = (step_height, 0.085)
bnd_dH = (0, 0.02)

f_bnd_L1 = (0.01, 0.15)
f_bnd_L2 = (-0.13, 0.1)
f_bnd_L3 = (0.01, 0.09)
f_bnd_L4 = (-0.13, 0.1)

h_bnd_L1 = (0.01, 0.1)
h_bnd_L2 = (-0.25, 0.1)
h_bnd_L3 = (0.01, 0.03)
h_bnd_L4 = (-0.1, 0.1)


# h, dh, dL1, dL2, dL3, dL4 = bezier_profile
bnds = [bnd_H, bnd_dH, f_bnd_L1, f_bnd_L2, f_bnd_L3, f_bnd_L4,
        bnd_H, bnd_dH, f_bnd_L1, f_bnd_L2, f_bnd_L3, f_bnd_L4,
        bnd_H, bnd_dH, h_bnd_L1, h_bnd_L2, h_bnd_L3, h_bnd_L4,
        bnd_H, bnd_dH, h_bnd_L1, h_bnd_L2, h_bnd_L3, h_bnd_L4]
result = differential_evolution(getTrajectoryCost, bnds, recombination=0.5, seed=1, workers=-1)
# min_ = minimize(getTrajectoryCost, bez_prof_init, method='Nelder-Mead',bounds=bnds, options={'disp': True, 'maxiter': 1000})
# min_ = minimize(getTrajectoryCost, bez_prof_init, method='SLSQP',bounds=bnds, options={'disp': True})

/home/guanlunlu/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:382: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  with DifferentialEvolutionSolver(func, bounds, args=args,


ttt tt0.09398603439331055tt t ttt tt
t t0.09443235397338867 t 0.09433603286743164 0.09421515464782715 0.09464025497436523    0.09577655792236328 0.09555268287658691[ 0.06117436  0.00112377  0.03826921 -0.04883928  0.01968604  0.00141474] 


0.095493555068969730.096097230911254880.0967111587524414
0.09579586982727051
0.096006870269775390.09617710113525390.09563922882080078 


0.09412026405334473

[ 0.05963439  0.0170144   0.02682775 -0.0451118   0.01247916 -0.08381564]

[ 0.05290474  0.01582424  0.05588626  0.07666542  0.01869331 -0.09282798]
[ 0.08072713  0.01431499  0.01118847 -0.10847992  0.02422457  0.0211843 ][ 0.0836815   0.00512689  0.0115392  -0.07075592  0.0229741   0.09032806]
0.09574484825134277[ 0.05030282  0.01842803  0.07631006 -0.20330856  0.01329032 -0.03852003]

[ 0.06098036  0.01308602  0.06018476 -0.21277249  0.01653205 -0.04858502]

[ 0.05370145  0.01827419  0.05662569 -0.23153754  0.01944983  0.05845143][ 0.05391029  0.01547477  0.07085775 -0.23802974  0.02849154  0

In [5]:
print(repr(result.x))

array([ 0.05619701,  0.00411106,  0.01690634, -0.03432745,  0.08628042,
       -0.09429632,  0.05316414,  0.00363167,  0.02571238,  0.04847964,
        0.01144883,  0.08482995,  0.07099504,  0.0061735 ,  0.04818854,
        0.00514284,  0.01187029, -0.0274283 ,  0.05789841,  0.01448661,
        0.01453597,  0.0163456 ,  0.01975994, -0.07417478])
