In [1]:
from cpg_fsm import *
from scipy.optimize import minimize
from scipy.optimize import differential_evolution

In [2]:
loop_freq = 100  # Hz
FSM = FiniteStateMachine(loop_freq)
t = time.time()
iter = 0

In [3]:
def getTrajectoryCost(bezier_profiles):
    global iter
    global t
    print("t", time.time()-t)
    t = time.time()
    bp = bezier_profiles.reshape(4, -1)
    print(bp[3])
    CORGI = Corgi(loop_freq, FSM)
    CORGI.standUp(0.8)
    CORGI.move(swing_profile=bp)
    print("iter", iter,"cost",CORGI.cost)
    iter += 1
    return CORGI.cost
    

In [4]:
bez_prof_init = np.array([[0.06, 0.01, 0.15, 0.05, 0.08, 0.06],
                          [0.06, 0.01, 0.15, 0.05, 0.08, 0.06],
                          [0.06, 0.01, 0.08, 0.05, 0.02, 0.1],
                          [0.06, 0.01, 0.08, 0.05, 0.02, 0.1]])
bez_prof_init = bez_prof_init.reshape(1, -1)[0]

step_height = 0.05
bnd_H = (step_height, 0.085)
bnd_dH = (0, 0.02)

f_bnd_L1 = (0.01, 0.15)
f_bnd_L2 = (-0.13, 0.1)
f_bnd_L3 = (0.01, 0.09)
f_bnd_L4 = (-0.13, 0.1)

h_bnd_L1 = (0.01, 0.1)
h_bnd_L2 = (-0.25, 0.1)
h_bnd_L3 = (0.01, 0.03)
h_bnd_L4 = (-0.1, 0.1)


# h, dh, dL1, dL2, dL3, dL4 = bezier_profile
bnds = [bnd_H, bnd_dH, f_bnd_L1, f_bnd_L2, f_bnd_L3, f_bnd_L4,
        bnd_H, bnd_dH, f_bnd_L1, f_bnd_L2, f_bnd_L3, f_bnd_L4,
        bnd_H, bnd_dH, h_bnd_L1, h_bnd_L2, h_bnd_L3, h_bnd_L4,
        bnd_H, bnd_dH, h_bnd_L1, h_bnd_L2, h_bnd_L3, h_bnd_L4]
result = differential_evolution(getTrajectoryCost, bnds, recombination=0.5, seed=1, workers=-1)
# min_ = minimize(getTrajectoryCost, bez_prof_init, method='Nelder-Mead',bounds=bnds, options={'disp': True, 'maxiter': 1000})
# min_ = minimize(getTrajectoryCost, bez_prof_init, method='SLSQP',bounds=bnds, options={'disp': True})

/home/guanlunlu/.local/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:382: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  with DifferentialEvolutionSolver(func, bounds, args=args,


ttttttt tt t ttt0.09454154968261719tt   t 0.09420204162597656  0.09432578086853027
    0.09491372108459473 0.095133781433105470.09552431106567383
 0.094886302947998050.09478402137756348
 0.094551324844360350.096173524856567380.096097946166992190.095772027969360350.096505880355834960.09676861763000488[ 0.08072713  0.01431499  0.01118847 -0.10847992  0.02422457  0.0211843 ]


0.09598398208618164


0.09643721580505371

[ 0.0836815   0.00512689  0.0115392  -0.07075592  0.0229741   0.09032806]

[ 0.06117436  0.00112377  0.03826921 -0.04883928  0.01968604  0.00141474][ 0.05290474  0.01582424  0.05588626  0.07666542  0.01869331 -0.09282798][0.06679454 0.0089871  0.03617077 0.01337519 0.01376011 0.07722737]


[ 0.07142177  0.01930576  0.0200357  -0.03857589  0.02256946 -0.07802338][ 0.05391029  0.01547477  0.07085775 -0.23802974  0.02849154  0.06181408][ 0.05569011  0.00961376  0.09248669 -0.02120638  0.01383259  0.0378885 ][ 0.06958815  0.00067917  0.05065171 -0.05305882  0.01180183  0.066637

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/guanlunlu/MBD_Corgi_python/script/cpg_fsm.py", line 331, in move
    self.legs[i].moveSwing(lf_sp)
  File "/home/guanlunlu/MBD_Corgi_python/script/cpg_fsm.py", line 130, in moveSwing
    tb_ = lk.InverseKinematicsPoly(sp)
  File "/home/guanlunlu/MBD_Corgi_python/script/LegKinematics.py", line 149, in InverseKinematicsPoly
    raise ValueError("Desired length exceed ", str(desired_length), "Point desired", str(point_G.T))
ValueError: ('Desired length exceed ', '0.34290262793141196', 'Point desired', '[[ 0.30876299 -0.14915638]]')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/guanlunlu/.local/lib/python3.8/site-pac

In [5]:
print(repr(result.x))

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "/home/guanlunlu/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_1131/4005089944.py", line 1, in <module>
    print(repr(result.x))
NameError: name 'result' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/guanlunlu/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2105, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/home/guanlunlu/.local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1396, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/guanlunlu/.local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1287, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/guanlunlu/.local/lib/python3.8/site-packages